name: Organize lists

on:
  push:
    branches:
      - master
    paths:
      - "data/v2/*.csv"

jobs:
  edit_lists:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/t145/black-mirror:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Organize lists
        run: |
          mlr --csv --quote-all sort -f provider,service_type,address_type,address_data,auth_name data/v2/dot.csv | sponge data/v2/dot.csv
          mlr --csv --quote-all sort -f provider,service_type,address_type,address_data data/v2/doh.csv | sponge data/v2/doh.csv
          mlr --csv --quote-all sort -f provider,service_type,address_type,address_data,auth_name data/v2/dnscrypt.csv | sponge data/v2/dnscrypt.csv
        shell: bash

      - name: Upload modified lists
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: lists
          path: |
            data/v2/*.csv
            exports/*
          retention-days: 1

  commit_changes:
    runs-on: ubuntu-latest
    needs: edit_lists
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download modified Sources
        uses: actions/download-artifact@v3
        with:
          name: lists

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ✨📚✨
